### ISSUE TITLE
"월간일정보기"에서 일정 클릭할 때 가끔 스크롤바가 생겼다가 사라져요.

### ISSUE THREAD

**Issue by jlucete** [loveliveall/llcal-front#13]
"월간일정보기"관련 이슈입니다. 
구글 크롬화면에서 왼쪽 배너가 나와있을 때 기준입니다. 

정확한 원인을 찾진 못했는데, 
월간일정들이 처음 로딩되고 나서, 이전에 클릭한 적 없던 일정을 클릭할 때 스크롤바가 생겼다가 사라져서
스크롤바 폭(width)만큼 캘린더가 리사이즈되었다가 원래 크기로 돌아가는 이슈가 있어요.

**Comment by loveliveall** [comment]
알려진 이슌데 쓸 때 불편한건 아니라서 냅뒀음 원인이 당장 보이는 것도 아니고.

**Comment by loveliveall** [comment]
12번 이슈에서 트랙하니까 닫음
