### ISSUE TITLE
금주의 비정기 이벤트 탭

### ISSUE THREAD

**Issue by seelightKR** [loveliveall/llcal-front#18]
장기일정(예약기간 등)이랑 정기일정이 캘린더에 많아서 비정기일정이 묻혀있는 경우가 많은듯

주차별로 니코나마나 라이브같은 비정기일정을 따로 모아서 띄워줄 수 있었으면 좋겠음

**Comment by loveliveall** [comment]
지금 상태에서도 캘린더에서 정기 일정 제외 / 예약 기간 제외 하면 볼 수는 있긴 한데...\
그냥 별도의 dedicated tab을 하나 만들어달란거지?

그럼 기준은 어떻게 잡을까 예약/알림 일정 제외, 정기 일정 제외해서 한 주 단위로?

**Comment by seelightKR** [comment]
모바일에서는 일일히 세팅 바꿔서 보기 귀찮으니까 ㅇㅇ 별도의 탭이 잇으면 좋겠다는거 터치 or 클릭하면 뜨는?

한주단위 or 오늘 포함 다음 7일로 생각했었는데 앞에꺼가 나을듯

**Comment by loveliveall** [comment]
이거 그냥 프리셋 기능으로 만드는게 나으려나? 필터 설정 조합을 하나의 프리셋으로 만들어서 저장하는...

저장 자체는 디바이스에 하게 되긴 할텐데 뭐 쓰는 장비가 맨날 바뀌는것도 아니고

**Comment by seelightKR** [comment]
'필터링이 간편했으면 좋겠다 '라기보단 '이번주에 무슨 이벤이 있는지 간편하게 확인할 수 있었으면 좋겠다'가 주 목적이라 필터링 프리셋 구현보다는 그냥 이번주의 이벤트만 모아서 보는 탭을 만드는 방식이 나을거같음

필터 프리셋을 만드는것 자체는 반대안하는데 이거랑은 별개의 건인듯

**Comment by loveliveall** [comment]
대시보드 형태로 구현했음. 확인하고 별 문제 없으면 이슈 close 부탁

**Comment by loveliveall** [comment]
대시보드 형태로 구현했음
