### ISSUE TITLE
API 엔드포인트 관련 문의

### ISSUE THREAD

**Issue by So-chiru** [loveliveall/llcal-front#27]
안녕하세요, 항상 캘린더 유용하게 잘 쓰고 있습니다!

다름이 아니라 콜표 사이트의 대시보드에 캘린더 데이터를 활용하여 라이브 (2주 이내 라이브 목록)와 생일 정보를 표시하도록 만들고 싶은데 (예시: https://github.com/So-chiru/llct/pull/175) 현재 사이트에서 제공 중인 ICS 엔드포인트를 활용하여 이를 제작해도 문제가 없는지 확인하고자 이슈를 남깁니다.

또한 사용에 문제가 없고 여유가 있으시다면 하나 건의드리고 싶은 것이 ICS 응답 데이터에 해당 일정의 정보를 확인할 수 있는 속성들이 추가되었으면 하는 바람이 있습니다...!

예를 들어,

```diff
BEGIN:VEVENT
UID:1000018@llcalendar
DTSTAMP:20210918T133838Z
DTSTART;TZID=Asia/Seoul;VALUE=DATE:20100801
DTEND;TZID=Asia/Seoul;VALUE=DATE:20100802
RRULE:FREQ=YEARLY
SUMMARY:타카미 치카 생일
LOCATION:
DESCRIPTION:타카미 치카의 생일입니다\n\n관련 성우: 이나미 안쥬
+ X-TYPE:BIRTHDAY
END:VEVENT
```

생일은 위와 같이 X-TYPE 속성이 추가되고

```diff
BEGIN:VEVENT
UID:95abad40-c7d5-405b-8bfb-5223405e99d8@llcalendar
DTSTAMP:20210918T133838Z
DTSTART;TZID=Asia/Seoul;VALUE=DATE:20220212
DTEND;TZID=Asia/Seoul;VALUE=DATE:20220213
SUMMARY:Aqours 6th LoveLive! 나고야 공연 DAY 1
LOCATION:반테린 돔 나고야
DESCRIPTION:バンテリンドーム ナゴヤ\n라이브 특설 사이트: https://www.lovelive-anime.jp/urano
 hoshi/sp_6thlive.php\n\n관련 성우: 이나미 안쥬\, 아이다 리카코\, 스와 나나카\, 코미야 아리사\, 사이토 
 슈카\, 코바야시 아이카\, 타카츠키 카나코\, 스즈키 아이나\, 후리하타 아이
+ X-TYPE:LIVE
+ X-LIVE:REGULAR
+ URL:https://www.lovelive-anime.jp/uranohoshi/sp_6thlive.php
END:VEVENT
```
라이브의 경우에는 위와 같이 X-TYPE과 URL (라이브 공지 URL, 일부 클라이언트는 이 필드의 정보를 표시 지원 ex: iOS 캘린더), 그리고 정말 제 흉측한 욕심이긴 하지만 X-LIVE (라이브 타입, 정규 : REGULAR, 기타 : OTHER) 가 추가되는 식입니다.

위 건의는 바쁘시거나 매번 수정하기 번거로우시다면 건너뛰어주시면 감사하겠습니다..!

다시 한번 캘린더 사이트 제작에 감사드리고 앞으로 더 발전되어 나갈 수 있기를 기원합니다!

**Comment by loveliveall** [comment]
안녕하세요.

1. ICS 엔드포인트는 현재 요청시에 DB 전체의 데이터를 읽고 정제해서 내리는 형식을 사용하고 있기 때문에 직접 사용하는건 약간 부담이 될 것 같아 보입니다.
2. 지금 구조에서 최소의 변경으로 작업하려면 요청주신 사항만 추가하고 llct 측 서버에서 시간단위로 ics 캐싱을 사용하거나 하는게 방법일것 같은데, 어차피 2주 이내의 라이브/생일 정보만 읽어오면 되는거라면 제쪽에서 api 엔드포인트를 하나 만드는 편이 가장 깔끔하게 떨어질듯 싶네요. 구현 자체가 어려운 부분은 아니니 인터페이스 쪽만 이 이슈에서 명확히 정의하고 PR 열어서 작업해 노티드리는 식으로 진행하면 될거 같습니다. 상세 내용은 아래쪽에서 좀 더 얘기할게요.
3. 정보 확인 속성의 경우, `X-TYPE` 은 2번의 api endpoint를 분리하는 식으로 해결을 볼 수 있을것 같습니다. 만약 api는 일원화하고 그 안에서 type을 구분하고 싶으신 경우 말씀해주세요. 그 방향으로 진행하는 것 자체는 큰 상관 없을것 같습니다.
4. 라이브 쪽 정보 속성의 경우
   - `URL` 필드의 경우엔 추가가 어렵지 않은 부분이니 추가하도록 하겠습니다. 다만 기존 이벤트들(최소한 미래 이벤트들은) 싹다 변경이 필요해서(...) 실제로 사용이 가능해지는건 좀 걸릴 것 같네요.
   - `X-LIVE` 필드의 경우엔 정규 라이브 기준을 '럽라 관련 이벤트이면서 + 공식 사이트([아쿠아](https://www.lovelive-anime.jp/uranohoshi/live.php), [니지](https://www.lovelive-anime.jp/nijigasaki/live.php), [리에라](https://www.lovelive-anime.jp/yuigaoka/live/))에 배너가 등록된 이벤트' 로 잡으면 될까요? 만약에 정규 라이브 정보'만' 필요한 경우라면 이 필드를 추가하기보단 그냥 새로 만드는 api 측에서 정규라이브 정보만 내려주는 쪽이 나을것 같습니다.

## API 인터페이스 초안

1. 기본적으로 application/json 타입으로 돌려주는걸 생각하고 있습니다. ics 포맷이 더 편하시다면 그쪽으로 작업해 드리겠습니다.
2. `GET http://cal-api.llasfans.net/api/llct/birthday`, `GET http://cal-api.llasfans.net/api/llct/live` 의 두 개 endpoint를 사용하고, 각각 2주 이내의 생일 목록 / 2주 이내의 정규 라이브 목록**만**을 돌려주며, 두 엔드포인트에서 사용하는 일정 object의 format은 동일하게 가져가려 합니다. 엔드포인트별로 필드 하나 두개 정도는 필요에 따라 가감할 수 있을것 같습니다.
3. 일정 object에 필요한 정보는 말씀주시면 협의해서 결정하는게 좋을 것 같습니다. ics 포맷을 사용하고 싶으시면 기존거에 요청주신 필드만 추가하면 될 것 같구요.

**Comment by So-chiru** [comment]
따로 엔드포인트를 파주신다니 배려해주셔서 감사합니다.

우선, 생일과 라이브 정보의 캐싱 기간이 달라 `GET http://cal-api.llasfans.net/api/llct/birthday`, `GET http://cal-api.llasfans.net/api/llct/live` 로 나눠주시는 편이 나을 것 같습니다.

제가 생각하고 데이터 캐싱 주기는

1. 생일 데이터는 2주 주기로 가져오고, 라이브 데이터는 최소한 D-DAY 1주 이전에는 D-DAY 정보를 표시해야 하기 때문에 생일 데이터보다 짧은 2일~5일 간격으로 가져올 예정입니다.
2. 서버가 모종의 이유로 종료되었을 때 저장된 캐시 데이터의 나이가 5일 이하인지 확인하고 오래되었다면 새로운 데이터로 받아올 예정이라 주기를 보증하지 못할 수 있습니다.

로 생각하고 있습니다. 다른 부분에 대해서는,

> X-LIVE 필드의 경우엔 정규 라이브 기준을 '럽라 관련 이벤트이면서 + 공식 사이트(아쿠아, 니지, 리에라)에 배너가 등록된 이벤트' 로 잡으면 될까요? 

네, 맞습니다.

> 만약에 정규 라이브 정보'만' 필요한 경우라면 이 필드를 추가하기보단 그냥 새로 만드는 api 측에서 정규라이브 정보만 내려주는 쪽이 나을것 같습니다

지금 캘린더에 있는 정보는 토크회 같은 비정규 라이브와 합쳐져 있어서 구별을 위해 제안드린 것인데 정규 라이브 데이터만 내려주신다면 말씀하신 대로 이 필드는 필요 없을 것 같습니다.

> 일정 object에 필요한 정보는 말씀주시면 협의해서 결정하는게 좋을 것 같습니다.

생일에 필요한 데이터는 `캐릭터 이름 (string)`, `일정의 시작일 (string, ISO 8601)` 정도고,

라이브에 필요한 데이터는 `일정의 이름 (string)`, `이벤트와 관련된 사이트 링크 (string)`, `일정의 시작 시각 (string, ISO 8601)`, `일정의 종료 시각 (string, ISO 8601)`, `캐릭터 이름 (string[])`, 그리고 가능하다면 `일정의 위치 (string)` 입니다.

이렇게 해서 제안드리는 타입은

```ts

interface LLCTResponseBase {
    id: string // 일정의 고유 ID (구별 전용)
    name: string // 일정의 이름
    characters: string[] // 관련된 캐릭터의 이름 배열
    start: string // ISO 8601 형식의 시작 시각
    end: string // ISO 8601 형식의 종료 시각
}

interface LLCTResponse extends LLCTResponseBase {
    url?: string // 이벤트와 관련된 사이트 링크
    location?: string // 이벤트와 관련된 장소
} 

type BirthdayResponse = LLCTResponseBase[]
type LiveResponse = LLCTResponse[]
```

입니다. 굳이 이런 타입이 아니더라도 결과가 어떻게 되든 정형화된 타입이라면 제가 파싱해볼 수 있도록 하겠습니다.

감사합니다!

**Comment by loveliveall** [comment]
캐릭터 이름의 경우는 [이 array](https://github.com/loveliveall/llcal-front/blob/828243ed31b91edf14879cb1fb0d82bb964f5462/src/commonData.ts#L50)에 있는 캐릭터 이름으로 내려드리고, 생일 관련 정보는 캐스트 생일을 제외한 캐릭터 생일만 내려드리도록 하겠습니다.

서버측 작업이 완료돼 사용 가능한 상태가 되면 이 이슈에 완료 코멘트 다는 방향으로 노티 드리도록 하겠습니다. 완료 코멘트 달 때 API 사용 방법도 같이 첨부 드리겠습니다. FYI, 정규 라이브 구분하는 부분 / URL 추가하는 부분은 서버측 작업 이후에 데이터 관련 수정 작업도 들어가야 해서 반영이 좀 늦어질 수도 있습니다.

아 그리고 노파심에 한 가지만 말씀드리면 라이브 일정의 경우 대부분 종료가 명확하지 않기 때문에 제가 임의로 종료 시간을 잡아두는 경우가 많으니(보통 2시간 반에서 3시간을 예상합니다) 종료 시간은 신뢰할 수 있는 정보가 아닙니다. + 라이브 일자 공지만 되고 시작 시간 정보가 아직 공개되지 않은 공연의 경우는 시작 시간이 0시 0분으로 잡혀서 나갈 수 있습니다. 2주 전이면 엥간하면 시작시간은 공지가 되어 있긴 하겠지만요.

이 이슈는 API 작업이 완료되고 llct 측에서 사용했을 때 문제 없음이 확인되고 나면 닫아주시면 됩니다.

**Comment by loveliveall** [comment]
작업 완료하여 아래 API 상세 Spec 전달 드립니다. 사용해보시고 문제있거나 / 추가 요청이 있으시면 말씀해주세요

# 개요

기본적으로 모든 엔드포인트는 요청이 주어진 시점을 기준으로 하여 3일 전 ~ 14일 후 까지의 기간 중에 **보이는 이벤트**를 반환합니다. 여기서 **보이는 이벤트**란 1. 이벤트의 종료 시간이 주어진 시점의 3일 전 이후이면서, 2. 이벤트의 시작 시간이 주어진 시점의 14일 후 이전인 이벤트를 의미합니다. 즉 주어진 기간에 조금이라도 걸치는 모든 이벤트가 반환된다고 보시면 됩니다. 전일 일정(ex,. 생일)의 경우 시작일의 00:00부터 종료일의 23:59까지 이어지는 것으로 해석합니다.

# API Specification

## `birthday` endpoint

- Request Endpoint: http://cal-api.llasfans.net/api/llct/birthday
- Content-Type: application/json
- Response body type:
   ```typescript
   type BirthdayResponse = {
     id: string, // `${entity_id}-${year}`
     character: string, // Name of character
     start: string, // YYYY-MM-dd formatted
   }[];
   ```

### Request Example
```http
GET http://cal-api.llasfans.net/api/llct/birthday HTTP/1.1
```

### Response Body Example
```json
[
  {
    "id": "22-2021",
    "character": "사쿠라우치 리코",
    "start": "2021-09-19"
  },
  {
    "id": "29-2021",
    "character": "쿠로사와 루비",
    "start": "2021-09-21"
  },
  {
    "id": "804-2021",
    "character": "헤안나 스미레",
    "start": "2021-09-28"
  }
]
```

## `live` endpoint

- Request Endpoint: http://cal-api.llasfans.net/api/llct/live
- Content-Type: application/json
- Response body type:
   ```typescript
   type LiveResponse = {
     id: string, // UUID
     name: string, // Title of event
     characters: string[], // List of names of characters related to the event
     start: string, // YYYY-MM-ddTHH:mm:ss+09:00
     end: string, // YYYY-MM-ddTHH:mm:ss+09:00
     url?: string,
     location?: string,
   }[];
   ```

### Request Example
```http
GET http://cal-api.llasfans.net/api/llct/live HTTP/1.1
```

### Response Body Example
```json
[
  {
    "id": "1c3d285d-60d7-4694-ac48-e41604c3b0ed",
    "name": "Guilty Kiss 2nd LoveLive! ～Retrun To Love ♡ Kiss Kiss Kiss～DAY 1",
    "characters": [
      "사쿠라우치 리코",
      "츠시마 요시코",
      "오하라 마리"
    ],
    "start": "2021-09-25T17:30:00+09:00",
    "end": "2021-09-25T20:00:00+09:00",
    "url": "https://www.lovelive-anime.jp/uranohoshi/sp_unit2021_GK.php",
    "location": "도쿄 가든 시어터"
  },
  {
    "id": "7b01ad9c-7639-4043-83ef-485b52d16841",
    "name": "Guilty Kiss 2nd LoveLive! ～Retrun To Love ♡ Kiss Kiss Kiss～DAY 2",
    "characters": [
      "사쿠라우치 리코",
      "츠시마 요시코",
      "오하라 마리"
    ],
    "start": "2021-09-26T16:30:00+09:00",
    "end": "2021-09-26T19:00:00+09:00",
    "url": "https://www.lovelive-anime.jp/uranohoshi/sp_unit2021_GK.php",
    "location": "도쿄 가든 시어터"
  }
]
```

### Notes
- `location` 필드의 경우 가능한 한국어 번역된 장소명을 넣으려고 하는 편입니다만 일본어 원어로 장소명이 들어가는 경우가 있을 수 있습니다.
- `name` 필드의 경우도 마찬가지로, 일정 제목은 한국어로 번역 하려는 편입니다만 번역이 애매하거나 한 경우 일본어 원어로 들어가는 경우가 있습니다.
- 말씀드렸다싶이 `end` 필드의 경우 신뢰할 수 있는 정보가 아닙니다. 참고용으로만 사용해주세요.
- 아직 명확한 시작 시간 공지가 되지 않은 공연의 경우 `start`는 고지된 날짜의 00:00+09:00 으로, `end`는 고지된 날짜의 23:59+09:00 으로 시간이 잡혀서 내려갑니다.
- 라이브 분류의 경우, 말씀드렸던대로 공식 라이브 페이지에 배너가 등록된 모든 이벤트를 라이브로 분류하려 했는데 찬찬히 살펴보니 [가사라지 공개 녹음](https://www.lovelive-anime.jp/nijigasaki/sp_gasaraji.php), [리리이베](https://www.lovelive-anime.jp/yuigaoka/live/sp_hms/) 등도 포함되어 있는 관계로 기준을 약간 변경해야 할 것 같습니다. 근데 딱히 명확한 기준이 있는건 아니고.... 배너가 등록된(i.e., 특설 사이트가 있는) 이벤트 중, 통념적으로 라이브라고 받아들여질만한 공연들을 라이브로 분류하도록 하겠습니다. 라이브로 분류되어야 할 것 같은데 그렇게 분류되지 않은 이벤트가 있거나, 혹은 그 반대의 경우가 발생하면 [메인 사이트](https://cal.llasfans.net) 의 '일정 추가 요청 보내기' 기능을 통해 변경 요청을 보내주세요. FYI, 라이브로 분류된 이벤트는 이제 [메인 사이트](https://cal.llasfans.net)에서 '러브 라이브' 카테고리로 별도 제공하고 있으니 이걸 통해 확인하셔도 됩니다.

**Comment by So-chiru** [comment]
이렇게 빠르게 구현해주셔서 감사합니다...! 위에서 언급한 대로 구현이 되어 있으니 더 의의 사항은 없을 것 같습니다. 좋은 하루 보내세요!
