### ISSUE TITLE
필터배너도 접기 기능이 있으면 좋을 것 같아요. 

### ISSUE THREAD

**Issue by jlucete** [loveliveall/llcal-front#8]
기타필터
성우/캐릭터필터
분류필터
도 각각 접고 열기가 가능하면 어떨까요?

**Comment by loveliveall** [comment]
아 요거 안그래도 하려다가 먼가 걸려서 안했었음 근데 하긴 해야댐 ㅇㅋ

**Comment by loveliveall** [comment]
구현했음. 확인하고 별 이슈 없으면 닫아주세요

**Comment by jlucete** [comment]
필터 대제목 폰트 사이즈 줄이면 어떨까? 
다른 카테고리들이랑 같은 사이즈 + 볼드처리(Option)

아 그리고 위 아래 간격 조절도 해주세요 ♥

**Comment by loveliveall** [comment]
https://github.com/loveliveall/llcal-front/commit/5d668227b6c064773b5f9f0519c6540728ade88c

함

**Comment by jlucete** [comment]
사랑해
