### ISSUE TITLE
"일정 추가 요청 보내기" 기능 개선 건의합니다.

### ISSUE THREAD

**Issue by jlucete** [loveliveall/llcal-front#9]
일정 추가를 위한 모든 정보를 적는 폼을 제공하고 요청자가 제출하면

관리자가 확인할 때 조금만 수정하고 등록을 누르면 일정이 바로 등록될 수 있게 하면 어떨까요?

[폼 예시]
일정 제목(\*):
기간(\*):
위치:
설명:
분류필터 태그:
멤버필터 태그:
기타필터 태그:

(*)는 필수사항입니다.

**Comment by loveliveall** [comment]
예전 버전 llcal 에서 비슷한 방식을 사용하긴 했는데.....

요건 좀 생각해봄
